baseURL = "https://lilyssleepyy.github.io/lilyobrien/"
relativeURLs = true
canonifyURLs = true
publishDir = "docs"
languageCode = "en-us"
title = "Lily O'Brien"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

